// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD58LLRg3w7qoczhtSxuHqGL-mOCKh7czs',
    appId: '1:343416576890:web:2eab66123c5f05616dd4c3',
    messagingSenderId: '343416576890',
    projectId: 'newstart-d7387',
    authDomain: 'newstart-d7387.firebaseapp.com',
    storageBucket: 'newstart-d7387.appspot.com',
    measurementId: 'G-3588CVJ14L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7tcxXPI7paHEDG2VPBtz24Y5IFFxOdw',
    appId: '1:343416576890:android:dfdff17e50c9e80e6dd4c3',
    messagingSenderId: '343416576890',
    projectId: 'newstart-d7387',
    storageBucket: 'newstart-d7387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFM5iDBj5XSyXYh6qDL8QWttgvXsrFR04',
    appId: '1:343416576890:ios:6c64d0372531273d6dd4c3',
    messagingSenderId: '343416576890',
    projectId: 'newstart-d7387',
    storageBucket: 'newstart-d7387.appspot.com',
    iosBundleId: 'com.example.newstart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFM5iDBj5XSyXYh6qDL8QWttgvXsrFR04',
    appId: '1:343416576890:ios:30a904577ebe60316dd4c3',
    messagingSenderId: '343416576890',
    projectId: 'newstart-d7387',
    storageBucket: 'newstart-d7387.appspot.com',
    iosBundleId: 'com.example.newstart.RunnerTests',
  );
}
